console.log("Gourmet", "Bistro", "script", "Loaded");
const restaurantName = "The Gourmet Bistro";
console.log(restaurantName);
let appetizerPrice = 8.99;
appetizerPrice = 9.99;
let mainCoursePrice = 15.99;
mainCoursePrice = 16.99;
let totalPrice = appetizerPrice + mainCoursePrice;
console.log("Total Price:", totalPrice);
let guests = 4;
guests = 5;
let pricePerGuest = totalPrice / guests;
pricePerGuest = totalPrice / guests;
let estimatedCost = pricePerGuest * guests;
estimatedCost = pricePerGuest * guests;
console.log("Estimated Cost:", estimatedCost);
const dishName = "Grilled Salmon";
const dishPrice = 18.99;
console.log(Featured, Dish, Grilled, Salmon, Price, dishPrice);
let welcomeMessage = "Welcome to The Gourmet Bistro!";
welcomeMessage = "Welcome to The Gourmet Bistro!";
console.log(welcomeMessage);
let menuMessage = "Seasonal menu items are updated regularly";
menuMessage = "Seasonal menu items are updated regularly";
console.log(menuMessage);
let chefName = "Chef Emilia Roux";
chefName = "Executive Chef Emilia Roux";
console.log("Chef Name:", chefName);
console.log(20,5);
document.getElementById("Welcome to The Gourmet Bistro")
document.getElementById("Seasonal menu items are updated regularly")